// Simple actions
export const ADD_TRANSACTION_ENTRY = 'ADD_TRANSACTION_ENTRY';
export const MODIFY_TRANSACTION_CATEGORY = 'MODIFY_TRANSACTION_CATEGORY';
export const MODIFY_TRANSACTION_AMOUNT = 'MODIFY_TRANSACTION_AMOUNT';
export const REMOVE_TRANSACTION_ENTRY = 'REMOVE_TRANSACTION_ENTRY';

export const ADD_CATEGORY_ENTRY = 'ADD_CATEGORY_ENTRY';
export const MODIFY_CATEGORY_NAME = 'MODIFY_CATEGORY_NAME';
export const SET_CATEGORY_BALANCE = 'SET_CATEGORY_BALANCE';
export const MODIFY_CATEGORY_BALANCE = 'MODIFY_CATEGORY_BALANCE';
export const REMOVE_CATEGORY_ENTRY = 'REMOVE_CATEGORY_ENTRY';

// Complex actions - consist of more than one simple action
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const CHANGE_TRANSACTION_CATEGORY = 'CHANGE_TRANSACTION_CATEGORY';
export const CHANGE_TRANSACTION_AMOUNT = 'CHANGE_TRANSACTION_CATEGORY';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CHANGE_CATEGORY_NAME = 'CHANGE_CATEGORY_NAME';
export const CHANGE_CATEGORY_BALANCE = 'CHANGE_CATEGORY_BALANCE';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
